### ISSUE TITLE
Improve Java documentation of consent component

### ISSUE THREAD

**Issue by alump** [vaadin/vaadin-cookie-consent-flow#64]
I can't get Consent indicator to show up. I tried both examples at https://vaadin.com/components/vaadin-cookie-consent/java-examples 

Are these examples correct? Neither get consent to show up on 14 RC1 application.

Used Spring Boot project starter RC1 as base. Tried to add example rows to constructor of view, and also at button click handler. Nothing is shown in UI.

**Comment by alump** [comment]
Ok, it works if you add it to view. But documentation doesn't mention it. One might assume it works like dialog (that you don't have to add to parent). So please clarify this in documentation (eg. show in example code that it's needs to be added to component tree).

**Comment by alump** [comment]
Also it looks like it needs to be added to right part of component tree (to route component directly?), please clarify this in documentation. At least when I added it to dialog component, i didn't get consent shown.

**Comment by anasmi** [comment]
Fixed by https://github.com/vaadin/vaadin-cookie-consent-flow/pull/86
